version: "3"

services:
  ujon-web:
    container_name: ujon-web
    build:
      context: .
      dockerfile: Dockerfile
    #      args:
    #        ENV_VARIABLE: ${ENV_VARIABLE}
    #        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - "3000:3000"

