import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import Navigation from "@/components/Navigation";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en" data-theme="light">
        <body>
        <div>
            <Navigation/>
        </div>
        {children}
        </body>
        </html>
    );
}
