import type {Metadata} from "next";
import {ReactNode} from "react";
import "@/styles/index.css"
import Header from "@/components/Header";
import {getMessages} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";
import {getUserLocale} from "@/services/locale";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{ children: ReactNode }>) {
    const locale = await getUserLocale();
    const messages = await getMessages();

    return (
        <html lang={locale}>
        <body>
        <NextIntlClientProvider messages={messages}>
            <Header/>
            {children}
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
