name: release

on:
  push:
    tags:
      - 'release*'
  workflow_dispatch:

env:
  image_name: ghcr.io/${{github.repository}}:${{github.ref_name}}-${GITHUB_SHA::6}

jobs:
  config:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check all variables
        run: |
          echo "github.repository: ${{github.repository}}"
          echo "github.repository_owner: ${{github.repository_owner}}"
          echo "github.sha: ${{github.sha}}"
          echo "github.ref_name: ${{github.ref_name}}"
          echo "secrets.GHCR_TOKEN: ${{secrets.GHCR_TOKEN}}"
          echo "env.image_name: ${{env.image_name}}"

  packaging:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run:
          docker build -f ./Dockerfile -t ${{env.image_name}} .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ${{env.image_name}}
